### ISSUE TITLE
Download Whole Website Instead of User Specific Information

### ISSUE THREAD

**Issue by einfachluki** [Gertje823/Vinted-Scraper#1]
Hey!
First of all, thank you very much for providing such wonderful tool! I wanted to ask, if it would be possible to scrape not only user specific data (by providing User ID), but rather the whole website itself?
Many thanks in advance!

**Comment by Gertje823** [comment]
Hi,

Unfortunately this script only scrapes the data from the api and puts it in a database.
I am not planning to implement a feature that will scrape the whole page.

What kind of info do you mean?
If you need some specific info that is also available through the api I can try to implement it in the script.

**Comment by einfachluki** [comment]
Oh okay! 
Actually I would need all the products posted on vinted.com as jpg file, not only the products posted by one or more users

**Comment by Gertje823** [comment]
You could do so by modifying the script so it starts with ` userid=0` and add `userid+=1` just before the end of the loop. This way you would loop over all users and download all their posts.

I tried the in the past but it is quite slow and inefficient but it works 😄
I downloaded about 5.400.000 items (300gb) in a couple days.
