### ISSUE TITLE
Video scraping?

### ISSUE THREAD

**Issue by yasavvym8** [Gertje823/Vinted-Scraper#10]
Hi all,

Thanks very much for the very easy to use project. I know next to nothing about coding so this is quite helpful.

My question is related to scraping videos, as there are some posts that included a video attached to the products. Is there any way to also download the videos too? Or perhaps some workaround that may work? Unless it actually has downloaded somewhere? Thank you again!

Edit: I should tack on to the end here that I am specifically hoping to use this for Depop. Thank you!

**Comment by Gertje823** [comment]
Glad to hear you find the project useful.

I was not aware of the product videos. 
I think it should be possible to also download videos.

Could you give me examples so I can have a look at it?

**Comment by yasavvym8** [comment]
Thank you very much for the speedy reply! Here is an example of a post that contains 4 pictures and one video to cap it off: 

https://www.depop.com/products/michelleshappyfinds-vintage-nutcracker-can-you-find/

**Comment by Gertje823** [comment]
Thank you for the example.
I just pushed the new changes.
The script will now also download videos from Depop .
