### ISSUE TITLE
Vinted full size profile picture

### ISSUE THREAD

**Issue by EmperorMagusCaligula** [Gertje823/Vinted-Scraper#11]
Hello,

First of all, many thanks for this great script that works very well!
**Anyway, when using it with a Vinted profile, it doesn't download the full size profile picture, but the 800px one!**

For exemple, please consider this profile: https://www.vinted.fr/api/v2/users/17898589/
The full size profile picture is this one: "full_size_url":"https://images1.vinted.net/t/02_00ac4_a3xvXwC9zVxTErQQR8ci994V/1664022638.jpeg?s=ee1ec9539a7cf9c690a1d348e099e87533c76cac"

Thanks in advance if you could upgrade the script!

Greetings from France!

**Comment by Gertje823** [comment]
Thanks for the tip. I fixed it in the latest commit 😃
