### ISSUE TITLE
User does not exist firing erroneously

### ISSUE THREAD

**Issue by 2ndNegative** [Gertje823/Vinted-Scraper#12]
I am getting the "User does not exist" error even though that User _does_ exist. 
![Scraper1](https://user-images.githubusercontent.com/44379855/193452551-0c84d1f1-9908-4b87-a38b-c1197ce3ff4b.png)
![Scraper2](https://user-images.githubusercontent.com/44379855/193452554-4a28228d-5c5c-4f0b-9dbf-92c7ef1b160f.png)

Attached two screenshots. As you can see, User 90683608 is shown as not existing, but does definitely exist.

**Comment by Gertje823** [comment]
It seems that it parses the line breaks to the api requests and therefore cannot find the user. I moved `USERID.strip()` to the beginning of the loop so it will strip the userid string before the api request. Could you check if it is working now?

**Comment by 2ndNegative** [comment]
I only tested with this specific user right now, but it works!

**Comment by 2ndNegative** [comment]
I let a longer list run now, and can confirm that it does still happen. With other users, but it still happens. I used a list of 500 users, and 120 of them fail.

**Comment by Gertje823** [comment]
I just tested it with a large list of users but I could not reproduce the error you are getting. The script now waits if it gets  a  _too many requests_ response. Could you check if you still get the error?

**Comment by 2ndNegative** [comment]
List now ran without errors! Will run it again for confirmation
