### ISSUE TITLE
Large Vinted profiles not downloaded in their entirety

### ISSUE THREAD

**Issue by EmperorMagusCaligula** [Gertje823/Vinted-Scraper#13]
Hello,

I noticed that for some large Vinted profiles (more than 100 articles for exemple), the script doesn't download the photos in their entirety.

Indeed, in that case the script needs to go on page 2, page 3, etc... of the JSON code and not only on page 1.

For exemple:
**https://www.vinted.fr/member/13204749-maylis3110
https://www.vinted.fr/api/v2/users/13204749/items?page=1&per_page=200000
https://www.vinted.fr/api/v2/users/13204749/items?page=2&per_page=200000**

At the bottom of each page can be found information about the pagination:
**"pagination":{"current_page":1,"total_pages":2,"total_entries":176,"per_page":96,"time":1665930854},"code":0}
"pagination":{"current_page":2,"total_pages":2,"total_entries":176,"per_page":96,"time":1665931444},"code":0}**

Thanks in advance if you could upgrade the script!

Greetings from France!

**Comment by Gertje823** [comment]
Thank you for pointing that out. I think they changed something in the backend. At the time I wrote that part of the script, I believe they did not limit the `per_page` parameter. 

I added support for multiple pages. It will now fetch all pages and then download all the items. 😄
