### ISSUE TITLE
Scraper fails with error at line 70

### ISSUE THREAD

**Issue by eytay** [Gertje823/Vinted-Scraper#15]
Hello,

Unable to use this to scrape depop profiles

C:\Downloads\depop>python scraper.py
  File "C:\Downloads\depop\scraper.py", line 70
    <title>Vinted-Scraper/scraper.py at main · Gertje823/Vinted-Scraper · GitHub</title>
                                             ^
SyntaxError: invalid character '·' (U+00B7)

I have this script in a folder with another download folder within that. users.txt is populated with a single account id.

Any help?

**Comment by Gertje823** [comment]
It looks like something is wrong with your python file.
How did you download the python file?

You can download the code [here](https://github.com/Gertje823/Vinted-Scraper/archive/refs/heads/main.zip)
