### ISSUE TITLE
RSS 

### ISSUE THREAD

**Issue by luravoid** [Gertje823/Vinted-Scraper#26]
Hi, have you thought about creating a rss feed for vinted? I wonder if it's possible with their api. I think it would be super useful

**Comment by Gertje823** [comment]
This is not within the scope of this project.

Maybe if there is enough interest I could make a separate repo for it.
What would you like to include in the rss feed? (e.g. items of users, items including specific keywords)

**Comment by luravoid** [comment]
It would be great if i could generate rss feeds from specific keywords and categories.
There are discord bots that are doing that but i think rss feed would be much more convenient to use.
https://github.com/2spy/Vinted-Discord-Bot
https://github.com/Androz2091/vinted-discord-bot

**Comment by luravoid** [comment]
It would be great if i could generate rss feeds from specific keywords and categories.
There are already discord bots that can do that but i think rss feed would be much more convenient to use.
https://github.com/2spy/Vinted-Discord-Bot
https://github.com/Androz2091/vinted-discord-bot

**Comment by luravoid** [comment]
You can also take a look on this ebay rss generator:
https://github.com/adamxp12/feedbay
