### ISSUE TITLE
Vinted sold items

### ISSUE THREAD

**Issue by EmperorMagusCaligula** [Gertje823/Vinted-Scraper#28]
Hi,

I don't remember if this question has already been asked.
**Do you think it's possible to download the sold items of a Vinted profile?**

The sold items still appear online but they obviously are removed from the URL "https://www.vinted.nl/api/v2/users/{USER_ID}/items?page={page}&per_page=200000". The code can't download them.

I guess these items are stored in another URL when they are sold until they are deleted by the user or by Vinted.

Greetings. EMG.

**Comment by Gertje823** [comment]
As far as I know, there is no way to get a list of a users sold items. Maybe there is some parameter when requesting the items that I'm not aware of. 

But for now I think that is not possible :(
