### ISSUE TITLE
Question - Please answer asap

### ISSUE THREAD

**Issue by a4441** [Gertje823/Vinted-Scraper#29]
How/When would using this breach Depop or Vinted's Terms of Services or Privacy policies?

**Comment by krolminety** [comment]
🥶

> [..]  Vinted's Terms of Services

- [vinted.pl/terms_and_conditions](url)


> [..] Privacy policies?

- [vinted.pl/privacy-policy](url)

**Comment by a4441** [comment]
I’m sure Depop states no scraping is allowed…

**Comment by Gertje823** [comment]
Thanks for bringing this to my attention. I created this script a while back to level up my python skills. I was not aware this may violate any terms of service. I added a disclaimer to the readme.
