### ISSUE TITLE
[feature request] Scrape my own favorites

### ISSUE THREAD

**Issue by bosbrand** [Gertje823/Vinted-Scraper#37]
I would love to be able to import my own favorites so I can organise them in google sheets or something.

**Comment by Gertje823** [comment]
This should be possible.
I will look in to adding this into the v2 branch.

**Comment by Gertje823** [comment]
Added in d036f4b
You can now download your favourites using the v2 branch `python main.py -f -o <your_user_id> -s <your_vinted_session>`
