### ISSUE TITLE
not clear how to use

### ISSUE THREAD

**Issue by bosbrand** [Gertje823/Vinted-Scraper#39]
Can you expand on the user manual a bit? What do you need to do to download your favorites for example? 
I've set the user txt. Then I open command prompt and type
` python scraper.py -u myUserID -f  -s mySessionID`

The result is 'no module named cloudscraper'.

**Comment by Gertje823** [comment]
Looks like you are trying to download your favorites using the old script.
Downloading favourites is only supported using the [v2](https://github.com/Gertje823/Vinted-Scraper/tree/v2) version.

You need to clone/download the v2 version and download the dependencies using `pip install -r requirements.txt` then you can use `python main.py -u myUserID -f  -s mySessionID` to download your favourites.

Hope this helps.

**Comment by bosbrand** [comment]
now it says -f is not recognized

**Comment by bosbrand** [comment]
Okay, I've found out that using the git clone command downloads v1. I downloaded v2 as a zip and copied it over the contents of v1. Now I have a main.py like you say. But when I run it it says 'no module named tqdm', with reference lines 1 and 8.

**Comment by Gertje823** [comment]
Looks like not all the dependencies were installed.
If you run `pip install -r requirements.txt` it should download all the dependencies including tqdm

**Comment by bosbrand** [comment]
Done. Somehow I had to try pip install twice before it installed the tqdm. Now I get an error 'list index out of range', when I try to pull my favorites.

**Comment by bosbrand** [comment]
dang, it seems to work now. Thanks so much for your support!

**Comment by bosbrand** [comment]
Only problem is that It times out after a few dozen items. Where is the SQLite db stored?

**Comment by bosbrand** [comment]
Turns out Vinted doesn't like me doing this. It throws my session and after that I had to accept a new user agreement which specifically says scraping is forbidden.
