### ISSUE TITLE
Scraper not working anymore?

### ISSUE THREAD

**Issue by EmperorMagusCaligula** [Gertje823/Vinted-Scraper#42]
Hi, I don't know if I'm the only one but since a few days the Scraper doesn't work anymore (it closes immediately).

Here is what I get as an error:

Traceback (most recent call last):
  File "C:\Users\...\main.py", line 31, in <module>
    vinted_session = v.create_session()
  File "C:\Users\...\Vinted.py", line 115, in create_session
    csrfToken = req.text.split('<meta name="csrf-token" content="')[1].split('"')[0]
IndexError: list index out of range

**Comment by Gertje823** [comment]
Thanks for opening this issue.
This is fixed in 16c52e05b715f54e5b61602a8629329495c5804c thanks to @factoffer66
