### ISSUE TITLE
[Feature Request] Scrape the number of like

### ISSUE THREAD

**Issue by rct31** [Gertje823/Vinted-Scraper#45]
Hi, 
I would like to order the t shirts by the number of likes. 

To do that, do you think it's possible to scrape the number of like of the items in order sort them by this number after all ?

Thanks,

**Comment by Gertje823** [comment]
If you are talking about Vinted, than it should be possible. There is a field called `favourite_count` for each item in the json response. I will try to implement this when I have the time.

**Comment by Gertje823** [comment]
Added in 562546a86504317687157f99316b4a1686a8faa0 Thanks to @arthur469
