### ISSUE TITLE
Is there any way to save as PNG as opposed to jpeg?

### ISSUE THREAD

**Issue by yasavvym8** [Gertje823/Vinted-Scraper#49]
Hi there, this is a great program and has worked for me every time. I'm wondering if there's a way to save all photos in lossless quality as opposed to JPG? I'm not sure if the program just downloads whatever the photo is uploaded as but I just wanted to check if this was possible. Thank you in advance

**Comment by Gertje823** [comment]
Unfortunately that is not possible. It just downloads the high res image that is returned by their API. The high res image is already better quality then the image displayed on the item page.
