### ISSUE TITLE
user does not exist

### ISSUE THREAD

**Issue by Maxbuster21** [Gertje823/Vinted-Scraper#5]
when i enter the user id the program says the user does not exist

i just puth the 8 digit number in the user text file and run te program, what is going wrong?

**Comment by Gertje823** [comment]
Just tested the script with a random user and it works for me. Could you give me the userid of the user and I will take a look at it?

**Comment by Maxbuster21** [comment]
42769696, if it works, could you send me the most up to date .py file?

kind greetings max

**Comment by Maxbuster21** [comment]
our is there something i need to setup next to the userid in the .txt file?

**Comment by Gertje823** [comment]
Seems to work:
```python
python3 scraper.py
  37641390
  Avatar saved to downloads/Avatars/37641390.jpeg
  ID=42769696
  Successfully created the directory downloads/42769696/
  Image saved to downloads/42769696/01_01d63_MgPEw7eEJbngJw1BaXjPELWZ.jpeg
  Image saved to downloads/42769696/01_012f3_xKPtkpwCbKJ8KEFrEVS5kRBT.jpeg
  Image saved to downloads/42769696/03_017e1_j6PEiqwFEK6k7qsuvCke9Mpi.jpeg
  Image saved to downloads/42769696/02_02075_tvn1BLqRgxgPsMkJuhQSX1Ys.jpeg
  Image saved to downloads/42769696/03_00580_hZmqsJGKcmx9TMUF9rcrH9dk.jpeg
  Image saved to downloads/42769696/02_0090d_JJGwpMzLWu6K52oVhP9RUsXT.jpeg
  Image saved to downloads/42769696/01_017ec_haMeotQdRjqEEedfJC6w2frv.jpeg
  Image saved to downloads/42769696/01_0252f_haehuSbDUnQha1Lrw596wPwD.jpeg
  Image saved to downloads/42769696/01_0112f_4CyBKos8oE3dFW6yLtC3CBNh.jpeg
  Image saved to downloads/42769696/03_026b9_B7MNVimmDzLWV3gMoRxPPVf4.jpeg
  Image saved to downloads/42769696/01_01c98_aBLKuz1YcDvDvzLTYVJtRcG2.jpeg
  Image saved to downloads/42769696/02_002e9_Usxo3S4eQ1S42C37vG5Dyqni.jpeg
  Image saved to downloads/42769696/01_02599_pfKMZGNVSGRhpGH5VhqHVrDv.jpeg  
```
Are you sure you did not put a space after the userid or you have a blank line above it in the txt file? Could you paste here the exact error you are getting?

**Comment by Maxbuster21** [comment]
Of is er nog iets wat ik mischien vergeet?

**Comment by Maxbuster21** [comment]
dankuwel! nu lijkt hij het te doen!

mag ik vragen f het normaal is dat hij alle foto's op een hoop gooit?
of kan ik nog ergens een sorteer instelling doen?

**Comment by Gertje823** [comment]
Top! Hij zet de foto's per gebruiker in een map en alle data wordt bijgehouden in de sqlite database. Het is dus normaal dat de foto's in de map door elkaar staan. 
De foto's worden opgeslagen met de bestandsnaam zoals ze ook heten op de Vinted server.
