### ISSUE TITLE
Scraper not working since yesterday

### ISSUE THREAD

**Issue by AsimoToast** [Gertje823/Vinted-Scraper#51]
out of function :( 
Traceback (most recent call last):
  File "C:\UsersX\Scraper\scraper.py", line 609, in <module>
    download_vinted_data(userids, session)
  File "C:\UsersX\Scraper\scraper.py", line 161, in download_vinted_data
    gender = data['gender']
KeyError: 'gender'

**Comment by Gertje823** [comment]
It looks like Vinted removed the `gender` field from the API json response. I will implement a fix for this

**Comment by Gertje823** [comment]
Should be fixed in [fc1bac6](https://github.com/Gertje823/Vinted-Scraper/commit/fc1bac64fd70d2805355b62c40bf12d48826b773)
