### ISSUE TITLE
Are you working on V2 or main branch?

### ISSUE THREAD

**Issue by adriangalilea** [Gertje823/Vinted-Scraper#56]
README states:

https://github.com/Gertje823/Vinted-Scraper/blob/bbdfbb8fd7e0cee12ff320a135e19565a2aea869/README.md?plain=1#L4

But last commit on that branch is 1 year ago, and latest changes go on main, so what is it?

**Comment by Gertje823** [comment]
I know. My plan was to do a complete rewrite of the script and start from scratch. But unfortunately I don't use the script myself that much and I am quite busy lately. I am still pushing fixes to the main branch to have at least one working version of the script. But I am not planning on implementing new features into the main branch. 

If you want to support this project, you could contribute to the project and open a PR on the v2 branch and I will check and merge it.
