### ISSUE TITLE
API Changes (not working)

### ISSUE THREAD

**Issue by AsimoToast** [Gertje823/Vinted-Scraper#57]
line 183, in download_vinted_data
    verification_phone = data['verification']['phone']['valid']
KeyError: 'phone'

I think Vinted API changed the phone sector since yesterday. Can you fix it ?

cheers

**Comment by TheDevilsMine** [comment]
Same issue here

**Comment by Gertje823** [comment]
Looks like they removed the `phone` verification from the API. I edited the script and the value of `verification_phone ` should now be `None` when the field is not found in the json response.
