### ISSUE TITLE
Private Messages

### ISSUE THREAD

**Issue by kioz89** [Gertje823/Vinted-Scraper#8]
Is there a possability to grab images in full res from private messages on vinted?

**Comment by Gertje823** [comment]
Should now be possible. Download the latest version and use the `-p` option.
Example: `python scraper.py -p -u <Your_UserID> -s "<your_vinted_fr_session>"`

**Comment by kioz89** [comment]
Wow that was fast. Just tried out and it gives back a keyerror 'msg_threads'  Just for the case i made a mistake my session id is the csrf-token i parsed from firefox site information?

**Comment by Gertje823** [comment]
The session id should be the _vinted_fr_session cookie

**Comment by kioz89** [comment]
Alright i was able to figure out where to get this cookie. Now the error changed:

line 81, in download_priv_msg
    if len(message['entity']['photos']) > 0:

**Comment by Gertje823** [comment]
Could you please post the whole error so I can take a look ?

**Comment by kioz89** [comment]
Creation of the directory failed or the folder already exists
Creation of the directory failed or the folder already exists
Traceback (most recent call last):
  File "C:\Users\kioz\Downloads\Vinted-Scraper-main\Vinted-Scraper\scraper.py", line 411, in <module>
    download_priv_msg(session_id, user_id)
  File "C:\Users\kioz\Downloads\Vinted-Scraper-main\Vinted-Scraper\scraper.py", line 81, in download_priv_msg
    if len(message['entity']['photos']) > 0:
KeyError: 'photos'

This?

**Comment by kioz89** [comment]
I will, give me a sec. Btw thanks for your hard work :)

**Comment by kioz89** [comment]
Works like a charm, thank you very much. Awesome.
